# Use postgres/example user/password credentials
version: '3.1'

services:

  todo-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123pos
      POSTGRES_USER: todo
    ports:
      - 5432:5432