logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.context: INFO
    org.springframework.web.servlet.handler: TRACE
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.mvc.method.annotation: INFO
    springfox.documentation: INFO
line:
  bot:
    channelToken: LeWnmp6zIAy0eHCJD7/oCOiobdj5SZNsyRvWzWo+FmlsxKQtY4NCS0bL9p4rRi3zzN5zq0Kbns2zHlRKznGd6ySsik5ujmytq9Gq90RKuvN9sbfZP0hWHhV6R1Iloz1BNYOUo23596JfOVp32vJLJwdB04t89/1O/w1cDnyilFU=
    channelSecret: 23a8f476fd2111b9920d2a7b66d14118
    handler:
      path: /webhook
jwt:
  secret: mumoo
spring:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          line:
            client-id: 1646673985
            client-secret: 9adfb27494d135f5732482cb348e4332
            clientName: line
            authorization-grant-type: authorization_code
            redirectUriTemplate: 'https://6652f693.ngrok.io/login/oauth2/code/{registrationId}'
            scope: profile
            client-authentication-method: basic
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId


flyway:
  locations: classpath:db/migration
server:
  use-forward-headers: true